name: hydrate_me
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.6.0
  logger: ^2.6.2
  json_annotation: ^4.9.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  uuid: ^4.5.1
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.9.1
  auto_size_text: ^3.0.0
  timeago: ^3.7.1
  from_css_color: ^2.0.0
  page_transition: ^2.2.1
  flutter_animate: ^4.5.2
  go_router: ^16.3.0
  mask_text_input_formatter: ^2.9.0
  all_validations_br: ^3.2.3
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/



